[package]
name = "civorum-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "civorum"
path = "src/main.rs"

[dependencies]
civorum-core = { path = "../core" }
civorum-mapgen = { path = "../mapgen" }
