[package]
name = "civorum-mapgen"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_chacha = "0.10.0"
noise = "0.9"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
